### ISSUE TITLE
Some references are not showing up in Bibliography

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/mn-templates-iso#12] opened 2019-11-02 19:24 UTC
Some typeset references don't appear in the bibliography. And, additionally, if I include footnotes in the showing ones, they'll stop rendering as well.

Please, refer to the sample:
[bibliography-references-issue.zip](https://github.com/metanorma/mn-templates-iso/files/3800863/bibliography-references-issue.zip)

**Comment by ronaldtse** [comment] 2019-11-03 03:16
Thanks. @manuel489 , could we stop positing zip files and post the snippet online instead? Like this:

```adoc
= Title

Etc
```

**Comment by manuelfuenmayor** [comment] 2019-11-03 12:43
Ok @ronaldtse , no problem.

(I've been doing it on this way because I understand that sometimes it may be time consuming to reproduce the issue. So, I include the .adoc file with its outputs for speed and demonstration purposes.)

**Comment by ronaldtse** [comment] 2019-11-03 15:52
@manuel489 : it is much faster if you provide all the "source information" outside the ZIP file. e.g. only the output files should go into the zip. The Adoc, the image, should all be directly included as content.

@opoudjis the morale of this ticket is actually this:

1. There are many ways people enter references "wrong". e.g.

```
* [[[ISO1234,ISO 1234 footnote:[draft]]]], _title_.    <== this crashes
```

2. People are not able to discover the correct method of entering footnotes:

```
* [[[ISO1234,ISO 1234]]] footnote:[draft], _title_.    <== this is correct
```

3. People don't know that the title is auto-fetched, and they need a way of overriding auto-fetch.

**Comment by opoudjis** [comment] 2019-11-04 00:29
@ronaldtse, since I'm the one actually working on these tickets, clearly I should have the final say on what I want to see in the zip files, and what is faster: _it's my workflow_. And I want to see the *.adoc in there. The salient snippet can be copy pasted into the ticket, but the source must be included in the zip file.

@ronaldtse I have documented the correct format in https://www.metanorma.com/author/iso/topics/markup/ :

````
If an ISO reference is in preparation, ISO/IEC DIR 2 dictates that details of the reference status be given as a footnote. In Asciidoc, this is done by giving the date as a double dash, and following the bibliographic anchor with a footnote macro:

* [[[ISO16634,ISO 16634:--]]] footnote:[Under preparation. (Stage at the time of publication ISO/DI
````

So (2) is not true. People are able to discover the correct method of entering footnotes. They just aren't looking for it. And, no, _I am not going to rewrite the documentation for a fourth time._ As we have already discussed several times. If your concern is that the documentation is not searchable or readable, someone else will need to rewrite it.

I don't see either (1) or (2) as something I can do anything else on. If you want documentation to get to people, and they won't read the documentation already in place, you will have to find alternatives. Embedding documentation in templates is in fact an alternative, but you don't want so much embedded as to make them useless. But that should be a task deferred to after @manuel489 finishes this set of tasks.

3: If (3) is a genuine feature request, I require a ticket from you. `:no-isobib:` will decline to use the functionality at all: are you requesting turning off fetch for individual references?

**Comment by ronaldtse** [comment] 2019-11-04 04:19
>So (2) is not true. 
Good that it isn't true, I couldn't even find it myself...

For 3, the request is to turn off for specific references. Any thoughts?

**Comment by opoudjis** [comment] 2019-11-06 13:49
> For 3, the request is to turn off for specific references. Any thoughts?

Again, I require a distinct ticket from you. Clearly, it is irrelevant to this ticket.

**Comment by ronaldtse** [comment] 2019-11-07 05:27
> Again, I require a distinct ticket from you. Clearly, it is irrelevant to this ticket.

You've done this, thanks.

> if I include footnotes in the showing ones, they'll stop rendering as well.

Can we add a warning when people add footnotes in the reference tag?

**Comment by manuelfuenmayor** [comment] 2019-11-07 12:08
> Can we add a warning when people add footnotes in the reference tag?

Sorry @ronaldtse and @opoudjis , I was wrong.

I was using the following markup for the footnotes `{blank}footnote:[text]`
But after reading the documentation of @opoudjis, I realized that I had to use  ` footnote:[text]`

For example:

(This doesn't work)
````
* [[[ISO_8000-102,ISO 8000-102:—]]]{blank}footnote:[To be published.], _Data quality -- Part 102: Master data: Exchange of characteristic data: Vocabulary_.
````



(This does work)
````
* [[[ISO_8000-102,ISO 8000-102:—]]] footnote:[To be published.], _Data quality -- Part 102: Master data: Exchange of characteristic data: Vocabulary_.
````

**Comment by ronaldtse** [comment] 2019-11-07 15:03
@manuel489 we should then document that this is a common error. I don't understand why we need the "comma" after the `[[[...]]]` anyway.

**Comment by manuelfuenmayor** [comment] 2019-11-07 15:11
> @manuel489 we should then document that this is a common error. I don't understand why we need the "comma" after the `[[[...]]]` anyway.

Ok @ronaldtse

**Comment by opoudjis** [comment] 2019-11-08 07:54
OK, this ticket scopes back to Manuel's original request. If there are any issues with references that are not reflected in existing documentation on metanorma.com, I will update that documentation; but making any existing documentation more discoverable is out of scope of this ticket.

**Comment by opoudjis** [comment] 2019-11-08 07:57
> @manuel489 we should then document that this is a common error. I don't understand why we need the "comma" after the [[[...]]] anyway.

@ronaldtse : You've misread. What works is

````
* [[[ISO_8000-102,ISO 8000-102:—]]] footnote:[To be published.], _Data quality -- Part 102: Master data: Exchange of characteristic data: Vocabulary_.
````

No comma there, the comma has been optional for a year. What is required is space between the brackets and the footnote; I had not anticipated `{blank}`. Let me see if I can allow it.

**Comment by opoudjis** [comment] 2019-11-08 08:03
Huh, the `{blank}` removes any spaces between the anchor and the footnote. OK, adjusting regex.

**Comment by opoudjis** [comment] 2019-11-08 08:10
The `{blank}` was not the issue. The issue is the en-dash instead of double dash for the year. This processes correctly:

````
* [[[ISO_8000-102,ISO 8000-102:--]]]{blank}footnote:[To be published.], _Data quality -- Part 102: Master data: Exchange of characteristic data: Vocabulary_.
````

The documentation is explicit:

````
If an ISO reference is in preparation, ISO/IEC DIR 2 dictates that details of the reference status be given as a footnote. In Asciidoc, this is done by giving the date as a double dash, and following the bibliographic anchor with a footnote macro:
````

Manuel has entered an em-dash instead of a double dash throughout. I will allow em-dash and en-dash to be recognised alongside double dash in the references, but the documentation is clear.

**Comment by opoudjis** [comment] 2019-11-08 08:46
All parts reference parsing was requiring space between comma and title: relaxed.

**Comment by opoudjis** [comment] 2019-11-08 08:51
The references are now all being processed correctly with no changes to Manuel's document. The one reference not being displayed as expected is ISO 8000-102: the relaton search for ISO 8000-102 is failing.

**Comment by opoudjis** [comment] 2019-11-08 09:04
That was because I wasn't putting the footnote back in. But requiring the footnote for undated entries is somewhat brutal: I will just issue a warning if it is missing.

**Comment by opoudjis** [comment] 2019-11-08 09:13
And the warning on a missing footnote is ISO, not standoc

**Comment by opoudjis** [comment] 2019-11-08 10:07
> Can we add a warning when people add footnotes in the reference tag?

A warning on malformed references is issued in general. I will add link to metanorma.com

**Closed as completed** 2019-11-08 10:50 UTC
Labels: bug

**Comment by ronaldtse** [comment] 2019-11-08 11:31
> That was because I wasn't putting the footnote back in. But requiring the footnote for undated entries is somewhat brutal: I will just issue a warning if it is missing.

What exactly do you mean? References to ISO 8000-102 were working yesterday without footnotes.

**Comment by opoudjis** [comment] 2019-11-08 13:41
I am referring to

> The one reference not being displayed as expected is ISO 8000-102: the relaton search for ISO 8000-102 is failing.

The reference was not fully working without the footnote: it was not recognising it as an ISO citation, and processing it with fallback processing, instead of populating the authoring organisation properly. As a result, it was not sorting in the right place. This has been addressed now.
